@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3OTA3MTYyLCJleHAiOjE3Mzc5MTA3NjJ9.XnrKoVymP7nuJIMXbLCpYK2UfD9QbdAVVrrPh4CJs9c

### Vérifier la racine de l'API
GET http://localhost:8989/
Content-Type: application/json

###

### Enregistrer un nouvel utilisateur
POST http://localhost:8989/auth/register
Content-Type: application/json

{
  "username": "Mitch",
  "email": "contact@michel-dufour.fr",
  "password": "password_1234"
}

### Obtenir un token JWT en se connectant
POST http://localhost:8989/auth/login
Content-Type: application/json

{
  "email": "contact@michel-dufour.fr",
  "password": "password_1234"
}

### Récupérer tous les comics
GET http://localhost:8989/comics
Content-Type: application/json

###

### Récupérer un comic par ID
GET http://localhost:8989/comics/1
Content-Type: application/json

###

### Créer un nouveau comic (avec token JWT)
POST http://localhost:8989/comics
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Example Comic test 2",
  "slug": "example-comic-test-2",
  "frontCover": "http://example.com/front-cover.jpg",
  "backCover": "http://example.com/back-cover.jpg",
  "description": "This is an example comic description.",
  "collection": "Hors-série",
  "tome": 2,
  "author": "Jane Doe"
}

###

### Mettre à jour un comic (avec token JWT)
PUT http://localhost:8989/comics/8
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Example Comic 2",
  "slug": "example-comic-2",
  "frontCover": "http://example.com/front-cover.jpg",
  "backCover": "http://example.com/back-cover.jpg",
  "description": "This is an example comic description.",
  "collection": "Hors-série",
  "tome": 2,
  "author": "Jane Doe"
}

###

### Supprimer un comic (avec token JWT)
DELETE http://localhost:8989/comics/10
Content-Type: application/json
Authorization: Bearer {{token}}

###