@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3ODk4MDgyLCJleHAiOjE3Mzc5MDE2ODJ9.OXVsRDYpsrb-1rqedPMe2mkEMkoznl2O3jTkr-W-UXU

### Vérifier la racine de l'API
GET http://localhost:8989/
Content-Type: application/json

###

### Enregistrer un nouvel utilisateur
POST http://localhost:8989/auth/register
Content-Type: application/json

{
  "username": "Mitch",
  "email": "contact@michel-dufour.fr",
  "password": "password_1234"
}

### Obtenir un token JWT en se connectant
POST http://localhost:8989/auth/login
Content-Type: application/json

{
  "email": "contact@michel-dufour.fr",
  "password": "password_1234"
}

### Récupérer tous les comics
GET http://localhost:8989/comics
Content-Type: application/json

###

### Récupérer un comic par ID
GET http://localhost:8989/comics/1
Content-Type: application/json

###

### Créer un nouveau comic (avec token JWT)
POST http://localhost:8989/comics
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Example Comic 2",
  "slug": "example-comic-2",
  "frontCover": "http://example.com/front-cover.jpg",
  "backCover": "http://example.com/back-cover.jpg",
  "description": "This is an example comic description.",
  "collection": "Hors-série",
  "tome": 2,
  "author": "Jane Doe"
}

###

